### ISSUE TITLE
Metadata isn't send

### ISSUE THREAD

**Issue by lukasbraach** [diraimondo/gmusicproxy#41]
Somehow no player can read metadata out of the files. I tried a few things and suggest that something in connection to eyed3 fails. The data gets written into the temporary file but does not seem to be received on the client side. Hope you can help. 

Good work yet :+1:

**Comment by diraimondo** [comment]
Could you provide the output (possibly with debug enabled) during the error?

**Comment by lukasbraach** [comment]
Sure: 

geg@gegroot:~/gmusicproxy$ python2.7 GMusicProxy --extended-m3u --debug
Google Play Music Proxy 1.0.3 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': '**auto**',
 'disable_all_access': False,
 'disable_version_check': False,
 'email': 'braachmusic@gmail.com',
 'extended_m3u': True,
 'host': 'geg-clan.com',
 'list_devices': False,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

authenticated
Fetching lastest version of gmusicproxy...
latest available version: 1.0.3
installed version: 1.0.3
Listening on port 9999...
request path: /get_song?id=da262fdc-1a11-39f7-b5ee-c05065ecd1d9
92.76.14.194 - - [02/Jan/2016 20:42:36] "GET /get_song?id=da262fdc-1a11-39f7-b5ee-c05065ecd1d9 HTTP/1.1" 200 -
ListTracks(args=[], kwargs={'start_token': None, 'max_results': 20000})
{u'kind': u'sj#trackList', u'data': {u'items': ['<1022 tracks>']}}
Streaming song with id 'da262fdc-1a11-39f7-b5ee-c05065ecd1d9': Flo Rida - How I Feel
{u'album': u'How I Feel',
 u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/OrTZM_b3K6AamMYrTnNq9bi2xH3_In5OMBC_LXUlmSjwveceUyi8L1neLqEADWe8ra1_BHyFwA'}],
 u'albumArtist': u'Flo Rida',
 u'albumId': u'Bec7w25bcisbumtdntvpo22hkdy',
 u'artist': u'Flo Rida',
 u'artistArtRef': [{u'url': u'http://lh3.googleusercontent.com/dVxpXGSUqAhRydsPi4luaMs1gVKKKrRfSGvgFWy1NO_mTvV5LZo-KAxkigCJBTo8tIkiK6kDWNc'}],
 u'artistId': [u'Afsyvsoz36ym7vhjzwz3htjqs7e'],
 u'composer': u'',
 u'contentType': u'2',
 u'creationTimestamp': u'1389299597185329',
 u'deleted': False,
 u'discNumber': 1,
 u'durationMillis': u'169000',
 u'estimatedSize': u'6784549',
 u'genre': u'Hip-Hop/Rap',
 u'id': u'da262fdc-1a11-39f7-b5ee-c05065ecd1d9',
 u'kind': u'sj#track',
 u'lastModifiedTimestamp': u'1451741579687650',
 u'nid': u'T23jfm2gadwlpsn74wiiaw26ham',
 u'playCount': 28,
 u'recentTimestamp': u'1403900023821000',
 u'storeId': u'T23jfm2gadwlpsn74wiiaw26ham',
 u'title': u'How I Feel',
 u'trackNumber': 1,
 u'trackType': u'8'}
No handlers could be found for logger "eyed3.id3"
GetStreamUrl(args=['da262fdc-1a11-39f7-b5ee-c05065ecd1d9', '003048BE315C', 'hi'], kwargs={})
https://r1---sn-25g7sn7y.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=77296c25d4aa2eb7&itag=25&source=skyjam&begin=0&upn=T6QyHAOr424&o=10831720071767143138&ratebypass=yes&ip=91.121.2.43&ipbits=0&expire=1451763847&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=617CB2C81ECD2976105546506077AA7A33287756.33C537AB079570FEB7184C66362E7A7B07BB48AD&key=cms1&mm=31&mn=sn-25g7sn7y&ms=au&mt=1451763459&mv=u&nh=IgpwcjAxLnBhcjEwKgkxMjcuMC4wLjE&pl=23
streaming url: https://r1---sn-25g7sn7y.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=77296c25d4aa2eb7&itag=25&source=skyjam&begin=0&upn=T6QyHAOr424&o=10831720071767143138&ratebypass=yes&ip=91.121.2.43&ipbits=0&expire=1451763847&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=617CB2C81ECD2976105546506077AA7A33287756.33C537AB079570FEB7184C66362E7A7B07BB48AD&key=cms1&mm=31&mn=sn-25g7sn7y&ms=au&mt=1451763459&mv=u&nh=IgpwcjAxLnBhcjEwKgkxMjcuMC4wLjE&pl=23

**Comment by diraimondo** [comment]
Sorry, for the VERY LATE reply: not so much time for this project.

I've tried to reproduce the problem: the sond id used in your log looks not still valid (not found).
I did a research using the artist and track title to look for another id: `curl 'http://sauron:9999/search_id?type=song&artist=flo%20rida&title=how%20i%20feel'`
The reported id is of different type: `T23jfm2gadwlpsn74wiiaw26ham`. 

This id works for me: `vlc http://sauron:9999/get_song?id=T23jfm2gadwlpsn74wiiaw26ham`.

Let me know if you can still reproduce the bug and how.

**Comment by lukasbraach** [comment]
Yeah the song id has been updated. But my player still doesn't receive the Metadata. I have tried it on Linux and Windows, always the same problem. And the worst thing: I don't know why this bug occurs. Maybe because I execute the proxy on a remote server? That's the only difference between your vlc command and mine. Hope that helps.

Thanks in advance!

**Comment by lukasbraach** [comment]
WTF... I think I fixed it and it was not a fault in your code...
Somehow my players can't read IDv3 tags when streaming and Windows doesn't display them in Windows Explorer. But when I download them, VLC can read the tags... everything. I deeply apologize for wasting your time.

**Comment by diraimondo** [comment]
I want to be sure that this is only a localized problem with you programs and not a non-standard way to create the mp3 file by gmusicproxy. I just concatenate the ID3 tag with the song file provided by Google api.
VLC should show the tags both in streaming than from local filesystem. Right?

Windows Explorer and the other players don't show the metadata. Right?
Can you produces other examples (mp3 files with ID3 tag) that works with these?

I'm closing the report, but reply on it if you get useful information.

**Comment by lukasbraach** [comment]
Seems to be a VLC issue, other players (e.g. good old mpg123) display the Metadata even when streaming. Maybe because you first send the metadata and then the music data?

**Comment by diraimondo** [comment]
I don't think that the metadata could be placed at the end: think about the streaming.

Ok, let me know if you can find an mp3 file with a different behavior with your players.

**Comment by adamprato** [comment]
Incidentally, I just spent a few hours trying to figure this out myself. Even if I curl the file I still don't get the id3 tag:

request path: /get_song?id=Tnnsje6y7f4h2rakcrulwlqcxsq
GetStoreTrack(args=['Tnnsje6y7f4h2rakcrulwlqcxsq'], kwargs={})
{u'albumArtRef': [{u'url': u'http://lh3.ggpht.com/EvTT_3TjJrO2jkZCQ4KZJDGU1PNgie5z4uKYKqmNVkwog4DFGcheDtgj2_Ebz_eS1BUVRWu6Qw'}], u'artistId': [u'Apimofcb7jpdp4twm7cxtjtnqb4'], u'composer': u'', u'year': 2014, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Rock The House Live!', u'title': u'Tall, Dark Handsome Stranger (Live At The Centrum/1990)', u'albumArtist': u'Heart', u'trackNumber': 9, u'discNumber': 1, u'albumAvailableForPurchase': False, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Tnnsje6y7f4h2rakcrulwlqcxsq', u'nid': u'Tnnsje6y7f4h2rakcrulwlqcxsq', u'estimatedSize': u'9458443', u'albumId': u'Buo7lryyztc4nkvm72rhzgxpkv4', u'genre': u'Rock', u'kind': u'sj#track', u'artist': u'Heart', u'durationMillis': u'236000'}
Streaming song with id 'Tnnsje6y7f4h2rakcrulwlqcxsq': Heart - Tall, Dark Handsome Stranger (Live At The Centrum/1990)
{u'album': u'Rock The House Live!',
 u'albumArtRef': [{u'url': u'http://lh3.ggpht.com/EvTT_3TjJrO2jkZCQ4KZJDGU1PNgie5z4uKYKqmNVkwog4DFGcheDtgj2_Ebz_eS1BUVRWu6Qw'}],
 u'albumArtist': u'Heart',
 u'albumAvailableForPurchase': False,
 u'albumId': u'Buo7lryyztc4nkvm72rhzgxpkv4',
 u'artist': u'Heart',
 u'artistId': [u'Apimofcb7jpdp4twm7cxtjtnqb4'],
 u'composer': u'',
 u'contentType': u'2',
 u'discNumber': 1,
 u'durationMillis': u'236000',
 u'estimatedSize': u'9458443',
 u'genre': u'Rock',
 u'kind': u'sj#track',
 u'nid': u'Tnnsje6y7f4h2rakcrulwlqcxsq',
 u'storeId': u'Tnnsje6y7f4h2rakcrulwlqcxsq',
 u'title': u'Tall, Dark Handsome Stranger (Live At The Centrum/1990)',
 u'trackAvailableForPurchase': True,
 u'trackAvailableForSubscription': True,
 u'trackNumber': 9,
 u'trackType': u'7',
 u'year': 2014}

$ id3v2 -l foo
foo: No ID3 tag
$ pip list | grep eyeD
eyeD3 (0.7.9)

**Comment by diraimondo** [comment]
is this an uploaded track? Does gmusicproxy show any error in debug log during the streaming of this track?

**Comment by adamprato** [comment]
It's not an uploaded track, it's a track from All Access. I don't see any error, but the line "Streaming song with id 'Tnnsje6y7f4h2rakcrulwlqcxsq': Heart - Tall, Dark Handsome Stranger (Live At The Centrum/1990)" seems to imply that it's in the section of _get_song() that sees that the info structure is there and it would be building the id3 tags using 'tags = eyed3.id3.Tag()' then writing it out with 'self.wfile.write(tagsBin)'

**Comment by adamprato** [comment]
If I comment out the unlink()
$ file /tmp/tmpTFtYqb
/tmp/tmpTFtYqb: Audio file with ID3 version 2.4.0
$ id3v2 -l /tmp/tmpTFtYqb
/tmp/tmpTFtYqb: No ID3 tag
$ strings /tmp/tmpTFtYqb | tail -5
(17)RockTIT2
Tall, Dark Handsome Stranger (Live At The Centrum/1990)TPE1
HeartTPE2
HeartTPOS
01TRCK

**Comment by diraimondo** [comment]
I was not able to find the track using the id of the track provided by your example. Using the web interface I'm not even able to find the same album 'Rock The House Live'.  Maybe some kind of geo-limitations...
Anyway: it looks that the tag is effectively created and you should be able to find it on top of the song in the mp3 file. 

Could you try to use/parse/play this mp3 with other programs? 
I'm assuming the (most) of the other tracks on the All Access catalog is working for you. Can you provide other problematic ids? 
If the problem raises only with some tracks, it could be related to some strange character in the metadata: a wrong escaping of gmusicproxy or a bug in eyed3.

**Comment by adamprato** [comment]
Nothing I've played has had the metadata. Can you give me an example of song id that seems to work and I can try it on my side? I'm wondering if the issue is with eyeD3 since even standard id3 tools do not see that the file has any id3 data in the file that was created.

**Comment by diraimondo** [comment]
Do you mean that you can't get ANY track with a working id3 tag?! :-|

On my daily installation:
`
$ curl 'http://sauron:9999/get_by_search?type=matches&artist=heart&title=Dark%20Handsome%20Stranger&exact=no'    
#EXTM3U
#EXTINF:244,Heart - Tall, Dark Handsome Stranger
http://sauron:9999/get_song?id=Tqaz3n7ccrd5tcxmr54fltrslfe
#EXTINF:243,Heart - Tall, Dark Handsome Stranger
http://sauron:9999/get_song?id=Tfqpwwjbhgu6zyakqwz6jw2lity
#EXTINF:243,Heart - Tall, Dark Handsome Stranger
http://sauron:9999/get_song?id=Tpvtyi5r32ovlcxs4eexax5ifda

$ curl -s 'http://sauron:9999/get_song?id=Tpvtyi5r32ovlcxs4eexax5ifda' > /tmp/testing.mp3
$ ls -l /tmp/testing.mp3 
-rw-r--r-- 1 mario mario 9996360 12 apr 19.30 /tmp/testing.mp3
$ file /tmp/testing.mp3 
/tmp/testing.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, Stereo

$ id3v2 -l /tmp/testing.mp3 
/tmp/testing.mp3: No ID3 tag

$ rm -f /tmp/testing.mp3
`
VLC works well too. It looks that id3v2 tool doesn't see the tag. I just put on top of the mp3 song the tag made by eyeD3. I'm not sure if this is the correct format but if you are able to find proper documentation, it would be nice.

What other tools doesn't recognize the embedded tag in a downloaded song? The tool id3v2 is the first one I face.

**Comment by adamprato** [comment]
VLC only shows the url when playing. I didn't try the playlist method since I was trying to slow down a song for transcribing. I think the goal would be to get something like id3v2 or id3 or similar tools to work. I can try to spend some time over the weekend and will reach out to you if I have any luck.

**Comment by adamprato** [comment]
I think this issue is player specific, not gmusicproxy.

* VLC shows the track information if playing an album with get_album
* VLC does not show the track information if playing with get_song.
* Foobar2000 does not show the track information with either get_album or get_song
* id3v2 does not show the tag information
* eyeD3 commandline shows it just fine
* File based players (foobar2000, subsonic, vlc) shows the tag information fine.

There may be a way to encode something specific for VLC or other streaming players. I'll investigate that and either submit a request and/or a patch :)

This issue should be closed.

**Comment by adamprato** [comment]
Oh, lastly, another reason I thought this was a tagging issue. Same file, differen't extension:

$ eyeD3 foo
Nothing to do
$ eyeD3 foo.mp3
eyed3.mp3.headers:WARNING: Lame tag CRC check failed
foo.mp3                                                [ 9.10 MB ]
-------------------------------------------------------------------------------
Time: 03:56     MPEG1, Layer III        [ 320 kb/s @ 44100 Hz - Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: Tall, Dark Handsome Stranger (Live At The Centrum/1990)
artist: Heart
album: Rock The House Live!
album artist: Heart
track: 9                genre: Rock (id 17)
disc: 1
FRONT_COVER Image: [Size: 84468 bytes] [Type: image/jpeg]
Description:

-------------------------------------------------------------------------------

not sure why it cares about the extension...

**Comment by adamprato** [comment]
Most recent experiment:

id3v2 seems to have an issue with v2.4 tags. It reads v1.1 and v2.3 just fine:
id3v2 -l w*mp3
wut.mp3: No ID3 tag
id3v1 tag info for wv11.mp3:
Title  : Gone With The Wind              Artist: Ella Fitzgerald
Album  : "Mack The Knife" Ella In Berli  Year:     , Genre: Jazz (8)
Comment:                                 Track: 1
wv11.mp3: No ID3v2 tag
id3v2 tag info for wv23.mp3:
APIC (Attached picture): ()[, 3]: image/jpeg, 39223 bytes
TALB (Album/Movie/Show title): "Mack The Knife" Ella In Berlin
TCON (Content type): Jazz (8)
TIT2 (Title/songname/content description): Gone With The Wind
TPE1 (Lead performer(s)/Soloist(s)): Ella Fitzgerald
TPE2 (Band/orchestra/accompaniment): Ella Fitzgerald
TPOS (Part of a set): 01
TRCK (Track number/Position in set): 01
wv23.mp3: No ID3v1 tag
wv24.mp3: No ID3 tag

So as an experiment I changed the tags.save() to:
tags.save(filename=tempFile.name, version=eyed3.id3.ID3_V1_0)

I tried that for ID3_v1_1, ID3_v2_3, ID3_v2_4

Neither foobar nor vlc change the titles, or show anything in metadata if you right click the stream and show the metadata. eyeD3 does show it just fine:

ID3_v1_1
/u/arp/gmp3/doot.mp3                                               [ 5.94 MB ]
No ID3 v1.x/v2.x tag found!

ID3_v2_3
/u/arp/gmp3/doot.mp3                                               [ 5.98 MB ]
ID3 v2.3:

$ id3v2 -l doot.mp3
id3v2 tag info for doot.mp3:
APIC (Attached picture): ()[, 3]: image/jpeg, 39223 bytes
TALB (Album/Movie/Show title): "Mack The Knife" Ella In Berlin
TCON (Content type): Jazz (8)
TIT2 (Title/songname/content description): Gone With The Wind
TPE1 (Lead performer(s)/Soloist(s)): Ella Fitzgerald
TPE2 (Band/orchestra/accompaniment): Ella Fitzgerald
TPOS (Part of a set): 01
TRCK (Track number/Position in set): 01
poot.mp3: No ID3v1 tag

ID3_v2_4
/u/arp/gmp3/doot.mp3                                               [ 5.98 MB ]
ID3 v2.4:

: arp_kiki/pts/28:0.53:gmp3; id3v2 -l doot.mp3
doot.mp3: No ID3 tag

So for whatever reason the tags.save() will not write any id3 v1.1 tags. However, I can take a file with v2.4 tags and eyeD3 will gladly convert it:

$ id3v2 -l doot.mp3
doot.mp3: No ID3 tag
$ eyeD3 doot.mp3
ID3 v2.4:
$ eyeD3 --to-v1 doot.mp3
Writing ID3 version v1.1
$ id3v2 -l doot.mp3
id3v1 tag info for doot.mp3:
Title  : Gone With The Wind              Artist: Ella Fitzgerald
Album  : "Mack The Knife" Ella In Berli  Year:     , Genre: Jazz (8)
Comment:                                 Track: 1
doot.mp3: No ID3v2 tag

So the eyeD3 script will write something in v1.1 but tags.save(filename=tempFile.name, version=eyed3.id3.ID3_V1_1) does not. I'll see if I can coerce tags.save() into writing something with v1.1 or v2.3 tags and see if that's what lets foobar2k or vlc show the metadata.

**Comment by adamprato** [comment]
Rather than spending time on trying to make the v1.1 tags work:

$ id3v2 -l doot.mp3
id3v1 tag info for doot.mp3:
Title  : Gone With The Wind              Artist: Ella Fitzgerald
Album  : "Mack The Knife" Ella In Berli  Year:     , Genre: Jazz (8)
Comment:                                 Track: 1
doot.mp3: No ID3v2 tag

I hacked the proxy so it always sends that file:

 316         self.wfile.write(open('doot.mp3','r').read())

( I tried various song id's and they all played that one song file)

So foobar2k/vlc *will not* read v1.1 / v2.3 / v2.4 tags it seems.

**Comment by adamprato** [comment]
Okay so to put this issue to bed (I'm surprised it's still open), because the tags are in a static location in an mp3 (v1 it's the last 128 bytes), a player would need to read the entire file first and then access the metadata. To work around that for MP3, the shoutcast protocol interleaves metadata at a metadata-interval. VLC and Foobar2K request ICY metadata as part of the HTTP request (the 'Icy-MetaData: 1' header), and the server responds with icy- headers; in particular icy-metaint for describing when the metadata is seen.

So the answer to this huge thread is:

- If you need a song title in a streaming media player, use /get_album to retrieve the playlist which contains artist/titkle information for each track.
- If you only want to play a single song in VLC/Foobar2K/etc and using the /get_song method *and* still need metadata, _get_song() would need to be rewritten to check if the client sent the icy-metadata header request, and if so respond with a stream formatted with "SHOUTcast Meta Title Streaming"

**Comment by adamprato** [comment]
https://adam.pra.to/tmp/txt/gmusicproxy-icy-diff.txt

That works in VLC and Foobar2K

**Comment by diraimondo** [comment]
Dear Adam,
thank you for your extensive work. In your analysis you talk about the right position of the tag in the file: I put the tag as head of the file: is it right?
I'll study your patch and I'll include it if it fit well in the code.

Thanks.

**Comment by diraimondo** [comment]
I've just tested your patch on a local version of gmusicproxy: I've tested it only with VLC 2.2.2 on Linux and streaming with the get_song I don't see all the fields of the metadata properly populated. Only the field "now playing" is filled. 
Are you able to find another mp3 file that, in streamed with hacked method as above, shows the metadata info on vlc or Foobar2K? 
About your patch: there are some redundant code but if necessary I can include it. What is the use of the new get_info method?

**Comment by adamprato** [comment]
yikes, sorry about the get_info stuff. that was an experiment I used for testing.

I don't believe we should expect the metadata to be populated for /get_song. I don't think streaming media players translate the StreamingTitle metadata into anything more than the "now playing" field. The window title for foobar2k and vlc change, which meets what I wanted. I'll check further to see if there are any other metadata fields that can be set via the ICY metadata.

**Comment by diraimondo** [comment]
I don't see why the id3 tag can't be read on-the-fly by VLC (or any other player) during the streaming of a song. I'm wondering if it is in the right position/format. A working example could help.

**Comment by adamprato** [comment]
Have you seen VLC display the metadata from a stream via /get_song? As of yet I haven't, which is why I wrote my patch. Incidentally, I see what you mean about redundant code. I assumed that was better than having so many if statements, but I can refactor that to be less redundant.

I know an old winamp developer. I've reached out to him to see if he has any pointers about reading id3v2 tags and http streams. I tried locating it in vlc code, but didn't come across anything yet.

**Comment by adamprato** [comment]
https://adam.pra.to/tmp/txt/gmusicproxy-icy-diff.txt -- I removed the experiment crap and de-duplicated the excess code. I'll see if there is any way to get vlc to read it on the fly but so far I've not found anything beyond the shoutcast methods.

**Comment by diraimondo** [comment]
Adam, I've merged your patch with few changes:
- when the shoutcast metadata protocol support is enabled the IDv3 tag is not sent (is it possible to do? we should fix the declared size and the content arrangement...) but you declared the size including the tag;
- enabling this ICY support, a player that support both the standards could be blocked to receive the (better) IDv3 information; this is why I made this support optional and disabled by default.

Now your are an official contributor. :-)

Could you test the final version on the git repository?

**Comment by adamprato** [comment]
Teamwork!

**Comment by adamprato** [comment]
Seems to work. Hopefully I can figure out how to get VLC/Foobar2K to do the right thing so we don't have to choose between ICY or ID3. In the meantime this does what I need :)
